;   boards.ini
;
;   common settings for pioarduino enviroment
;
;   remarks:
;       - adds src/lib/arduino to and src/lib include path
;       - adds libraries common for all projects to lib_deps
;
;==============================================================================
[arduino]
;-----------------------------------------------------------------------------
framework = arduino

; ;   only compile files in src_dir and exclude subfolders
; src_filter = 
;     +<*>
;     -<lib/*/*> 

lib_deps =
    ${env.lib_deps}

; 	etlcpp/Embedded Template Library@^20.37.0
;     bblanchon/ArduinoJson @ ^7.0.4

build_flags =
    -I lib/litekit/include

lib_ignore =
    toolkit

;   monitor_flags = 
;       --raw

;-----------------------------------------------------------------------------
;   see https://docs.platformio.org/en/latest/core/userguide/device/cmd_monitor.html#cmd-device-monitor-filters
;
;   direct      display ansi colors
;   time        timestamp prompt
  
;   monitor_filters = direct
