;	platformio.h
;
;	remarks:
;		- use dedicated targets for different hardware build
;
;   see also:
; 		- https://docs.platformio.org/page/projectconf.html


;==============================================================================
[platformio]
;------------------------------------------------------------------------------
default_envs = test_d1

extra_configs = 
	boards.ini
	boards-esp8266.ini


;==============================================================================
[env]
;------------------------------------------------------------------------------
;   add common libraries for all targets

; lib_deps =
;     arminjo/IRMP @ ^3.6.3

;==============================================================================
[env:test_d1]
;------------------------------------------------------------------------------
extends = d1_mini

; lib_deps = 
;     ${d1_mini.lib_deps}
;     arminjo/IRMP @ ^3.6.3

build_flags =
    ${d1_mini.build_flags}
    -D TARGET=test_d1

; upload_port = com3
; monitor_port = com3
