;   platformio-litekit.ini
;
;   dedicated PlatformIO test configuration for litekit

;==============================================================================
[platformio]
;------------------------------------------------------------------------------
default_envs = test_litekit_rysta
test_dir = lib/litekit/test

extra_configs =
    target-arduino.ini
    target-esp8266.ini

;==============================================================================
[env]
;------------------------------------------------------------------------------
;   common libraries for all targets

lib_deps =
    makuna/NeoPixelBus@^2.8.4

;==============================================================================
[env:test_litekit_rysta]
;------------------------------------------------------------------------------
extends = rysta

test_build_src = no
test_filter = test_litekit_core/*

build_flags =
    ${rysta.build_flags}
    -D LITEKIT_TESTS=1

extra_scripts =
    ${rysta.extra_scripts}