;	platformio.h
;
;	remarks:
;		- use dedicated targets for different hardware build
;
;   see also:
; 		- https://docs.platformio.org/page/projectconf.html


;==============================================================================
[platformio]
;------------------------------------------------------------------------------
default_envs = bee_rysta

extra_configs = 
	target-arduino.ini
	target-esp8266.ini

;==============================================================================
[env]
;------------------------------------------------------------------------------
;   common libraries for all targets

lib_deps =
    makuna/NeoPixelBus@^2.7.0

;==============================================================================
[env:bee_d1]
;------------------------------------------------------------------------------
extends = d1_mini

build_flags =
    ${d1_mini.build_flags}
    -D TARGET=bee_d1


;==============================================================================
[env:bee_rysta]
;------------------------------------------------------------------------------
extends = rysta

build_flags =
    ${rysta.build_flags}
    -D TARGET=bee_rysta


;==============================================================================
[env:test_litekit_rysta]
;------------------------------------------------------------------------------
extends = rysta

test_build_src = no
; test_filter = test_litekit_core/*

build_flags =
    ${rysta.build_flags}
    -D LITEKIT_TESTS=1

; monitor_port = com3
