;   target-arduino.ini
;
;   common settings for arduino enviroment
;
;   see LICENSE for terms

;==============================================================================
[arduino]
;-----------------------------------------------------------------------------
framework = arduino

lib_deps =
    ${env.lib_deps}

build_flags =
    -I lib/litekit-arduino/include
    -I lib/litekit/include
    -D NO_GLOBAL_INSTANCES

lib_ignore =
    toolkit

;   required for ansi color codes in serial monitor
monitor_flags = 
    --raw

;-----------------------------------------------------------------------------
;   see https://docs.platformio.org/en/latest/core/userguide/device/cmd_monitor.html#cmd-device-monitor-filters
;
;   direct      display ansi colors
;   time        timestamp prompt
  
monitor_filters = direct
